macro(add_subprojets parent)
	file(GLOB dirs LIST_DIRECTORIES true ${parent}/*)
	foreach(dir ${dirs})
		if(IS_DIRECTORY ${dir} AND NOT ${dir} STREQUAL ${CMAKE_BINARY_DIR})
			if(NOT EXISTS ${dir}/CMakeLists.txt)
				add_subprojets(${dir})
			else()
				add_subdirectory(${dir})
			endif()
		endif()
	endforeach()	
endmacro()

macro(add_thirdparts)
	set(THIRDPARTS_DIR ${CMAKE_SOURCE_DIR}/thirdparts)
	file(GLOB_RECURSE PROJECTS ${THIRDPARTS_DIR}/*.cmake)
	foreach(PROJECT ${PROJECTS})
		include(${PROJECT})
	endforeach()
endmacro()

macro(add_thirddepen TARGET)
	set(LIBRARIES ${ARGV})
	list(REMOVE_AT LIBRARIES 0)
	foreach(LIBRARY ${LIBRARIES})
		add_dependencies(${TARGET} ${LIBRARY})
		target_include_directories(${TARGET} PUBLIC ${${LIBRARY}_LINK_INC})
		target_link_directories(${TARGET} PUBLIC ${${LIBRARY}_LINK_DIR})
		target_link_libraries(${TARGET} -ldl -lpthread ${${LIBRARY}_LINK_TAR})
	endforeach()
endmacro()